# Generated by Django 4.2.23 on 2025-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Moderation'), ('published', 'Published'), ('flagged', 'Flagged by AI')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('sad', '😢'), ('fire', '🔥'), ('heart', '❤️'), ('pray', '🙏'), ('amen', '✝️')], max_length=20),
        ),
    ]
