# Generated by Django 4.2.25 on 2025-11-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_temp_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the verification link expires', null=True),
        ),
    ]
