# Generated by Django 4.2.25 on 2025-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_verification_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, help_text='6-digit verification code', max_length=6, null=True),
        ),
    ]
