# Generated by Django 4.2.25 on 2025-11-01 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='prayer_requests.prayerrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_supports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('prayer_request', 'user')},
            },
        ),
    ]
