# Generated by Django 4.2.25 on 2025-11-01 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer_requests', '0002_prayersupport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrayerSupport',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE prayer_requests_prayerrequest
                        ADD COLUMN new_id uuid;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        UPDATE prayer_requests_prayerrequest
                        SET new_id = (
                            substr(md5(id::text), 1, 8) || '-' ||
                            substr(md5(id::text), 9, 4) || '-' ||
                            substr(md5(id::text), 13, 4) || '-' ||
                            substr(md5(id::text), 17, 4) || '-' ||
                            substr(md5(id::text), 21, 12)
                        )::uuid;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE prayer_requests_prayerrequest
                        ALTER COLUMN new_id SET NOT NULL;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE prayer_requests_prayerrequest
                        DROP CONSTRAINT IF EXISTS prayer_requests_prayerrequest_pkey;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE prayer_requests_prayerrequest
                        DROP COLUMN id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE prayer_requests_prayerrequest
                        RENAME COLUMN new_id TO id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE prayer_requests_prayerrequest
                        ADD PRIMARY KEY (id);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='prayerrequest',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='ai_moderation_feedback',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='content',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='post',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='prayer_count',
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='answered_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='answered_scripture',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='short_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('answered', 'Answered')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('anonymous', 'Anonymous')], default='public', max_length=12),
        ),
        migrations.CreateModel(
            name='PrayerInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('prayed', 'Prayed'), ('encourage', 'Encourage')], default='prayed', max_length=12)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('prayed', 'Prayed'), ('answered', 'Answered')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_prayer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prayernotification',
            name='prayer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='prayer_requests.prayerrequest'),
        ),
        migrations.AddField(
            model_name='prayernotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerinteraction',
            name='prayer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='prayer_requests.prayerrequest'),
        ),
        migrations.AddField(
            model_name='prayerinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='prayerinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('interaction_type', 'prayed')), fields=('prayer_request', 'user', 'interaction_type'), name='unique_prayer_per_user'),
        ),
    ]
