# Generated by Django 4.2.23 on 2025-07-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(help_text="e.g., 'image/jpeg', 'application/pdf'", max_length=50)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('ai_moderation', models.JSONField(blank=True, default=dict, help_text='AI moderation feedback for the file.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
