# Generated by Django 4.2.23 on 2025-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(help_text="e.g., 'image/jpeg', 'application/pdf'", max_length=255),
        ),
    ]
